### ISSUE TITLE
Example Program in README.md not worked.

### ISSUE THREAD

**Issue by zw963** [tarcieri/cool.io#42]
```ruby
cool.io.connection :echo_server_connection do
  on_connect do
    puts "#{remote_addr}:#{remote_port} connected"
  end
```

Where does cool be defined?

**Comment by repeatedly** [comment]
Since v1.3, cool.io doesn't require 'cool.io/dsl' by default.
I forgot to update README. Just fixed: https://github.com/tarcieri/cool.io/commit/de16378bf19e7d9b22eb27519305e3c134d8ffff

Thanks.

**Comment by zw963** [comment]
Could you please explain about following sentence means for me? please.
```
Sorry folks, Cool.io is retired.
Please check out Celluloid::IO instead. 
```

Why I see activity, Cool.io is better than Celluloid ?

**Comment by repeatedly** [comment]
This is written by original author and he is now working on Celluloid.

> Cool.io is better than Celluloid ?

It depends on situations. I use cool.io for fluentd's IO layer.
Fluentd is mainly based on CRuby for now and cool.io is faster and compact than Celluloid.
This is why I still maintain cool.io.

**Comment by zw963** [comment]
Thanks.

I think those messages should contact the author to be moved?

anyway, it just similarity, not the same, and both maintained.

**Comment by tarcieri** [comment]
Feel free to remove them. They were added when I was no longer maintaining the project because I switched to working on Celluloid instead, but since it's maintained they can be removed.
